development:
  adapter: postgresql
  encoding: unicode
  database: ryw_development
  username: ryw
  password: passw0rd

test:
  adapter: postgresql
  encoding: unicode
  database: ryw_test
  username: ryw
  password: passw0rd

production:
  adapter: postgresql
  encoding: unicode
  database: ryw_production
  username: ryw
  password: passw0rd
